#version 430 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout (binding = 0, std430) readonly buffer inputArray {
	float[100] inArray;
};

layout (binding = 1, std430) writeonly buffer outputArray {
	float[100] outArray;
};

uniform float multiply = 2.5f;

void main() {
	// Simple test compute shader to multiply each element in an input array by a specified value in parallel
	uvec3 globalID = gl_GlobalInvocationID.xyz;

	outArray[globalID.x] = inArray[globalID.x] * multiply;
}